@SchoolGether.Api_HostAddress = http://localhost:5265

GET {{SchoolGether.Api_HostAddress}}/api/v1/health
Accept: application/json

###

GET {{SchoolGether.Api_HostAddress}}/api/v1/health/ready
Accept: application/json

###

GET {{SchoolGether.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###
